/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package dddSample

import kotlin.test.Test
import kotlin.test.assertFailsWith

class AppTest {
    @Test
    fun testAppThrowException() {
        assertFailsWith<Exception> { App().createUser("a", "b", "c") }
    }
}
